/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.satotats.trial.gip

import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.UserRecord

fun main() {
    val app = FirebaseApp.initializeApp("stao_tats")

    val auth = FirebaseAuth.getInstance(app)
    auth.createUser(UserRecord.CreateRequest().setEmail("hogemail@mail.com").setPassword("hogehogehoge"))
}
